### ISSUE TITLE
User properties consideration

### ISSUE THREAD

**Issue by assadsiddiqui** [crexi-dev/rate-limiter#105]
Since it is the library specifically for rules, can I assume that the client information is already retrieved through instance of IHttpContextAccessor and injected into this library? So I should not mainly worry about getting client information from some token rather have a class for Client with all kind of information (like ClientId, Region) but use that class to determine what kind of rules apply.

**Comment by sviataslau** [comment]
Hello, thank your for asking. 

You got it right. 
Basically you build your own representation of a user which makes sense in a context of library you're building.
