### ISSUE TITLE
Rules configuration clarification

### ISSUE THREAD

**Issue by moseshvili** [crexi-dev/rate-limiter#138]
In provided examples there are two possible ways to configure limit rates which opposes to each other: Endpoint(API resource) vs Region(US/EU based)

> Some examples of request-limiting rules (you could imagine any others)
> - X requests per timespan;
> - a certain timespan passed since the last call;
> - for US-based tokens, we use X requests per timespan, for EU-based - certain timespan passed since the last call.

> The goal is to design a class(-es) that manage rate limits for every provided API resource by a set of provided configurable and extendable rules. 

Should both of them be supported? If yes, there could be possible cases where we need to introduce priorities for these possible configurations. Or can go simple way and make rules configuration only based on API resources?

Thanks in advance!
Giorgi

**Comment by sviataslau** [comment]
Hi Giorgi! 
Thanks for asking.

Those are just two examples of limiting rules, though you can create your own.

Anyways, a combination of rules per API resource should be supported.
For simplicity let's assume you assign a list of rules to an endpoint and if any of them fail — you get rate limited. 

Lmk if you need more clarification.

Thank you!

**Comment by moseshvili** [comment]
Thanks Slava!
