### ISSUE TITLE
Couple Questions About Rate Limiter Design - Elliot Sasson

### ISSUE THREAD

**Issue by esass10** [crexi-dev/rate-limiter#232]
1. How should I handle client identification for rate-limiting purposes? Should I consider different access tokens for the same client or assume one access token per client?
2. How should multiple rules be combined? Should they be enforced in a particular order, or should all rules be checked simultaneously for each request?
3. Should I be aware of any specific concurrency or thread safety requirements?

Thanks!

**Comment by sviataslau** [comment]
Hi!
Great questions!

> How should I handle client identification for rate-limiting purposes? Should I consider different access tokens for the same client or assume one access token per client?

Let's assume a token uniquely identifies each client. As for the token itself, you're not building the authentication layer, and you don't care how the token was generated; think a client is making a request, and that client has a token and some other associated metadata.

> How should multiple rules be combined? Should they be enforced in a particular order, or should all rules be checked simultaneously for each request?

The goal is to be able to configure a unique combination of rules for each resource. As long as this is achieved, we're good. For simplicity, we could treat those rules as logical ORs.

> Should I be aware of any specific concurrency or thread safety requirements?

We assume the resources will be accessed concurrently, as in real APIs, so the access rules should also support that.

Please let me know if something is still unclear.

Thank you!
