### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by lumalav** [crexi-dev/rate-limiter#236]
Do we need to include a WebApi project to actually test the RateLimiter by referencing it? or implementing the limiter and the tests is enough?

**Comment by sviataslau** [comment]
Hi! Thanks for asking.

Just implementing the library with a good test coverage is enough.

**Comment by lumalav** [comment]
> Hi! Thanks for asking.
> 
> Just implementing the library with a good test coverage is enough.

Thank you! I might have gone a little too far then 😅
