### ISSUE TITLE
Questions - (Scott Pierro)

### ISSUE THREAD

**Issue by Cow4Dinner** [crexi-dev/rate-limiter#239]
Hello!

1. Can I assume the responses to the other closed issues here apply in my case as well?
2. Does policy enforcement need to support a clustered environment or can I assume a single node?

**Comment by sviataslau** [comment]
Hi! 

Yes, those responses apply to all the submissions, so feel free to browse them if that helps. However, if you encounter any controversy, please don't hesitate to ask for clarification.

As for the environment, great question! Let's assume a single node to keep it simple.

**Comment by Cow4Dinner** [comment]
Thanks
