### ISSUE TITLE
configurability and extensibility

### ISSUE THREAD

**Issue by aiodintsov** [crexi-dev/rate-limiter#246]
What do you mean exactly by

>  _configurable_ and _extendable_ rules

Does extensibility mean that new rule types may be introduced? I.e. ability to implement fixed windows, sliding window, leaky bucket, token bucket, and any other type of rule and be able to easily embed it in (requiring recompilation, since new code is introduced)?

OR does it mean that additional user properties (other than token and region) could be incorporated (ex: Tier (paid, free, premium, trial), IP source, referrer, etc) - and without updating the library these additional data points would be discoverable and possible to use in both rule definition and processing?

OR something else not covered above?

What do you mean by:

> ...for a third one - both A + B, etc. Any combination of rules should be possible;

In real life rate limiters fail on any single rule failure. For example if there is a daily, monthly and an interval limits - if any of them is exhausted - api call is not honored. However "any combination of rules" may also mean "OR" logic, in a sense that all must fail for a rule to fail.

So should there be Any( list of rules ) or All ( list of rules ) logic or just any set of rules (but All must satisfy, which is more real-world)

When it mentions rules A + B is there an intent to define rule configurations once and then reuse it, or just having ability to define more than one rule per endpoint? Sudo:

Version 1:
```
endpoint /a: (interval 1s 10)
endpoint /b: (fixed 1d 10000)
endpoint /c: (interval 1s 10) (fixed 1d 10000)
```

Version 2:
```
rules:
  10per1s: (interval 1s 10)
  10kper1d: (fixed 1d 10000)
endpoints:
  /a: 10per1s
  /b: 10kper1d
  /c: 10per1s, 10kper1d
```

**Comment by rgarf81** [comment]
> Does extensibility mean that new rule types may be introduced?

Correct. If a product requirement came in for a new rule, how easily can it be introduced. No worries about recompilation.

> So should there be Any( list of rules ) or All ( list of rules ) logic or just any set of rules (but All must satisfy, which is more real-world)

Any set of rules per endpoint, but all must satisfy. If an endpoint is configured to check >1 rule, ALL must pass. If one fails, the request is rejected.
