### ISSUE TITLE
default and fallback rules?

### ISSUE THREAD

**Issue by aiodintsov** [crexi-dev/rate-limiter#247]
Should there be a possibility to have wildcard matches, fallbacks or default rules?

i.e. sudo:

```
endpoints:
  /a: (interval 1s 10)
  /b: (fixed 1d 10000)
  '*': (fixed 1s 10) // all endpoints are limited at 10 requests per second, if other rules don't match
```

**Comment by rgarf81** [comment]
No need for this exercise, we can assume an endpoint without a rate limit rule is open for consumption.
