### ISSUE TITLE
Change project type Class Library from Web Project

### ISSUE THREAD

**Issue by danielkern** [crexi-dev/rate-limiter#26]
Is it possible to change the project type from Class Library to Web API Project?

I started developing the code using attributes but there's a lot of workaround to make ActionFilterAttributes work with a class library.

I can either change the project type or move the logic from ActionFilterAttributes to other configurable filter method but before doing it I thought of asking if changing the project type is an option.

Thanks.

**Comment by sviataslau** [comment]
Hello.

Sure, go for it.
