### ISSUE TITLE
Library usage

### ISSUE THREAD

**Issue by jameslfcheng** [crexi-dev/rate-limiter#264]
Hi team,

While the question calls for the implementation of a class for the Rate Limiter, is the usage of the .NET native library `RateLimiting` allowed?

**Comment by rgarf81** [comment]
Hello @jameslfcheng, for this process we do not want you to configure that, but rather roll your own. In a production state where we aren't evaluating candidacy, absolutely an appropriate approach and question. But this is to see how you would design/implement your own.

**Comment by jameslfcheng** [comment]
@rgarf81 Sounds good. That's what I understood too, but I just wanted to make sure.
Thanks for the confirmation!
