### ISSUE TITLE
Q: Rule processing and priority (David Craig)

### ISSUE THREAD

**Issue by TestBenchNet** [crexi-dev/rate-limiter#41]
A need clarification on how rate limiting rules are processed, please review the items below and advise. 

Assumptions:
1) Each rule is simple (i.e. Consumer must be registered with API, Resource A can only be consumed 10 times / minute, etc.)
2) Some rules are more expensive than others to test, because they require more DB access, calculation, etc.
3) Some rules are just more important (i.e. If a user isn't allowed to access Resource B, it doesn't matter how many times per minute they have tried)

Questions:
1) Are these assumptions valid?
2) Once access has been denied per one rule, do we care about any of the others?

Scenarios:
1) Sequence matters, so rules are weighted and important rules run first, but they must be run in order. 
	1a) Once one rule fails, the rest aren't even executed.
	1b) Even if a rule fails, the rest still execute because we want to know the results.

2) Sequence doesn't matter, rules have no weight and can be executed in any order.
	2a) Once one rule fails, we can attempt to stop others (but as they would be running in parallel, there is no guarantee how many actually ran).
	2b) Even if a rule fails, the rest still execute because we want to know the results.

It really comes down to a balance of performance and reporting, and what is important for us.

**Comment by sviataslau** [comment]
Hi David,
Thanks for the thorough and good questions.

We can agree that all rules are equally simple, i.e., have the same or no weight. 
So we can check them in any order (or the order they were defined) and don't execute others if one fails.
