### ISSUE TITLE
Should I merely configure existing rate-limiting library or implement my own?

### ISSUE THREAD

**Issue by NatiaBekauri** [crexi-dev/rate-limiter#73]
Hello. I have a question about the task. We all know there exists implementing library with it's classes and ability to configure rate limiting. Do you mean I should use existing implementation and configure it to work with test API I will suggest in the project or you are asking to implement rate limiting "by hand", not with library?
Thank you in advance.

**Comment by v-zubritsky** [comment]
Hello. The task is to implement such a library, which could in theory be integrated then into some application. 

Just keep in mind that you don't need to cover all the cases, existing libraries on the market usually do, neither you should use any web framework like aspnetcore or a real database in your implementation. Proper rate limiting library design, a few rules and a set of tests is the goal here. Refer to the task description and feel free to create another issue in case of further questions.

Hope this helps.

**Comment by NatiaBekauri** [comment]
> Hello. The task is to implement such a library, which could in theory be integrated then into some application.
> 
> Just keep in mind that you don't need to cover all the cases, existing libraries on the market usually do, neither you should use any web framework like aspnetcore or a real database in your implementation. Proper rate limiting library design, a few rules and a set of tests is the goal here. Refer to the task description and feel free to create another issue in case of further questions.
> 
> Hope this helps.

Thank you very much!
